### ISSUE TITLE
Add import data from DTN code and populate Admin page fields in respective tabs

### ISSUE THREAD

**Issue by chukon** [aquaaerobic/AquaNeredaImportData#3]

**Comment by chukon** [comment]
Ready to test DTN Import for Admin Pages

**Comment by bquimby** [comment]
Did a quick check of the DTN import function. And noticed the following issues (see also attached report with comments). This was for a design I am working on with pre-EQ, AGS reactors, and sludge buffer only. Have not checked post-eq or water buffer at this point. The import was done in the dev version of APD. For many of the issues noted here, values are being correctly brought into the admin report page, but are not correctly being displayed on the design report.

PRE-EQ
1. Design report is not properly displaying the "NPHP Provided" value (it is properly imported on the admin report page

AGS REACTORS
1. Basin dimensions are not properly displayed on design report (but are being imported to the admin report page correctly)
2. Process depth is not properly displayed on design report (but is being imported to the admin report page correctly)
3. Basin volume is not being pulled in at all through the DTN import.

SLUDGE BUFFER
1. Metric value for max flow rate is not being pulled in through the DTN import.

Will follow this up with more issues as I do more testing.
[dtn import check 01.pdf](https://github.com/aquaaerobic/AquaNeredaImportData/files/1188094/dtn.import.check.01.pdf)

**Comment by chukon** [comment]
Brett, I am currently updating the Prelim report with new fields from Admin screen. Thanks
